--===========================================================
-- >> Magnitude Analysis
--===========================================================
-- Find total cusotmers by countries
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT
category,
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

-- What is the total revenue generated by each category?
SELECT
pr.category,
SUM(fs.sales_amount) AS total_revenue
FROM gold.dim_products pr
LEFT JOIN gold.fact_sales fs
ON pr.product_key = fs.product_key -- Nested join
GROUP BY pr.category
ORDER BY total_revenue DESC -- Taking significantly higher time to execute than below query

SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key -- Hash join
GROUP BY p.category
ORDER BY total_revenue DESC

SELECT * FROM gold.fact_sales
SELECT * FROM gold.dim_products

-- What is the total revenue generated by each customer?
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of items sold across countries?
SELECT
c.country,
SUM(f.quantity) AS total_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC
